name: CI

on: [push]

jobs:
  evan_test_job:

    runs-on: ubuntu-latest
    name: A job to greet you

    steps:
      - name: Greet action step
        id: greet1
        uses: asmallkite/evan-actions
        with:
          who-to-greet: 'Evan zheng li'   
      - name: Get the output name
        run: echo "The time was ${{ steps.greet1.outputs.time }}"
